version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/cookingblog
      - RECOMMENDATION_SERVICE_URL=http://recommendation:5000
    depends_on:
      - mongo
      - recommendation
    networks:
      - app-network

  recommendation:
    build: ./recommendation_service
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/cookingblog
    volumes:
      - ./recommendation_service:/app
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: 